spring.application.name=ALMIUX

# ** Configura la URL de conexión a la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/almiux_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# ** Usuario de la base de datos (Esto cambienlo amigos, según sea su caso)
spring.datasource.username=root

# ** Contraseña de la base de datos (Esto tambi{en amigos, es su contraseña)
spring.datasource.password=kalebtor

# ** Driver JDBC para MySQL 8+
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ** Dialecto SQL que Hibernate usará para generar queries compatibles con MySQL 8
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ** update: actualiza el esquema sin borrar datos; usar create-drop solo en pruebas
spring.jpa.hibernate.ddl-auto=update

# ** Imprime en consola cada query SQL ejecutada por Hibernate (Útil en desarrollo)
spring.jpa.show-sql=true

# ** Formatea el SQL impreso para que sea legible
spring.jpa.properties.hibernate.format_sql=true

# ** Puerto en el que corre el servidor (8080 es el default de Spring Boot)
server.port=8080

# Conexion MySQL Hostinger
spring.datasource.url=jdbc:mysql://srv1592.hstgr.io:3306/u709123045_almiux_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=u709123045_almiux
spring.datasource.password=ALMIUx123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Logs SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto
server.port=8080